apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 5
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          ports:
            - containerPort: 8080
